# Generated by Django 2.2 on 2019-05-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Is this listing to be published?', verbose_name='Is this listing published?'),
        ),
    ]
